version: "3.5"

services:
  broker1:
    container_name: broker1
    image: netifi/broker:${DOCKER_BROKER_IMAGE_VERSION}
    environment:
      - "BROKER_SERVER_OPTS=-Dnetifi.broker.ssl.disabled=${NETIFI_BROKER_SSL_DISABLED} -Dnetifi.broker.cluster.clusterName=${NETIFI_BROKER_CLUSTER_CLUSTERNAME} -Dnetifi.authentication.0.accessKey=${NETIFI_AUTHENTICATION_0_ACCESSKEY} -Dnetifi.authentication.0.accessToken=${NETIFI_AUTHENTICATION_0_ACCESSTOKEN} -Dnetifi.broker.admin.accessKey=${NETIFI_BROKER_ADMIN_ACCESSKEY} -Dnetifi.broker.admin.accessToken=${NETIFI_BROKER_ADMIN_ACCESSTOKEN} -Dnetifi.broker.admin.address=0.0.0.0 -Dnetifi.broker.admin.publicAddress=host.docker.internal -Dnetifi.broker.admin.port=6001 -Dnetifi.broker.cluster.address=0.0.0.0 -Dnetifi.broker.cluster.publicAddress=host.docker.internal -Dnetifi.broker.cluster.port=7001 -Dnetifi.broker.tcp.address=0.0.0.0 -Dnetifi.broker.tcp.publicAddress=host.docker.internal -Dnetifi.broker.tcp.port=8001 -Dnetifi.broker.websocket.address=0.0.0.0 -Dnetifi.broker.websocket.publicAddress=host.docker.internal -Dnetifi.broker.websocket.port=8101"
    ports:
      - "6001:6001"
      - "7001:7001"
      - "8001:8001"
      - "8101:8101"

  example-service1:
    container_name: example-service1
    image: netifi-broadcast-example/service
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - broker1

  example-service2:
    container_name: example-service2
    image: netifi-broadcast-example/service
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - broker1

  example-service3:
    container_name: example-service3
    image: netifi-broadcast-example/service
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - broker1
